### ISSUE TITLE
space-before-func-paren conflicts with async arrow functions

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/eslint-config-rocketchat#1]
ESLint throws error for `async () =>`, expecting `async() =>`.

**Comment by sampaiodiego** [comment]
I've seen that before but I don't know what to do 😞

**Comment by tassoevan** [comment]
Maybe overwrite the rule as

     space-before-function-paren: ["error", {"anonymous": "always", "named": "never", "asyncArrow": "always"}]

can do the trick.

**Comment by sampaiodiego** [comment]
fixed already
