### ISSUE TITLE
ESLINT_LEGACY_OBJECT_REST_SPREAD

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/eslint-config-rocketchat#2]
[ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "@rocket.chat/eslint-config")

**Comment by sampaiodiego** [comment]
fixed by d54e123505b567d97e79a0f85a21aabafc7f6918
