### ISSUE TITLE
Can `import/order` handle `index` as `sibling`?

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/eslint-config-rocketchat#9]
The following code of mine has been rejected by ESLint:

```js
import { Form } from './index';
import { FormItem } from './Item';
import notes from './README.md';
```

because the `import/order` rule doesn't define where "index" import should be placed: https://github.com/RocketChat/eslint-config-rocketchat/blob/e707d311f8f71d7f8311518ab0c97668649af3f6/rules/imports.js#L157

I'd like to suggest the following:

```js
'import/order': ['error', {
  'newlines-between': 'always',
  groups: ['builtin', 'external', 'internal', ['parent', 'sibling', 'index']]
}],
```

**Comment by sampaiodiego** [comment]
I agree =)
